### ISSUE TITLE
lien mort dans le readme

### ISSUE THREAD

**Issue by DreamsVoid** [nightwolf93/Crystal#1]
https://mega.co.nz/#!35QzxTYR!WRqRkmiUOE1kF5T6-V9FFElUobmHQFvvpMfq-cmWtSo n'est plus un lien fonctionnel.

Avez-vous un autre lien vers votre base de données?

**Comment by nightwolf93** [comment]
Je n'ai plus les fichiers pour la DB, le projet a 6 ans :/
